version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "3000:80"
        volumes:
            - ./:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        
    php:
        image: php:fpm
        volumes:
            - ./:/code
        
